Remade the color output of the makefile
Signed-off-by: Dan Printzell <xwildn00bx@gmail.com>

diff --git a/webserver/Makefile b/webserver/Makefile
--- a/webserver/Makefile
+++ b/webserver/Makefile
@@ -2,14 +2,20 @@ PROJECT := QDHTTP
 SHELL = bash
 
 CC ?= gcc
-CFLAGS := -Wall -Wextra -Werror -Iinclude -std=gnu1x -finline-functions -fPIC -fPIE -pipe
-LFLAGS :=
+CFLAGS := -Iinclude -std=gnu1x -finline-functions -fPIC -fPIE -pipe
+LFLAGS := -lm
+WARNINGS := -Wall -Wextra -Wshadow
+WARNINGS += -Wfloat-equal -Wmissing-prototypes -Wunused-value -Wunused-parameter
+WARNINGS += -Wmissing-declarations -Wstrict-prototypes -Wmissing-prototypes
+WARNINGS += -Wsign-compare -Wconversion -Wcast-align -Wparentheses
+WARNINGS += -Wsequence-point -Wundef
+WARNINGS += -Wpointer-arith -Wnested-externs -Wredundant-decls
+WARNINGS += -Wdisabled-optimization
 
 SRC := src/
 OBJ := objects/
 BIN := bin/
 
-CFLAGS += -D_DEFAULT_SOURCE
 
 # == Options ==
 
@@ -18,10 +24,10 @@ CFLAGS += -fdiagnostics-color=always
 endif
 
 ifdef RELEASE
-CFLAGS += -O2
+CFLAGS += -O2 -DDNDEBUG
 LFLAGS += -Wl,-O1
 else
-CFLAGS += -ggdb -Og
+CFLAGS += -ggdb3 -Og
 endif
 
 ifndef NO_ARCH_TUNE
@@ -33,6 +39,14 @@ CFLAGS += -flto
 LFLAGS += -flto
 endif
 
+ifndef NO_WERROR
+WARNINGS += -Werror
+endif
+
+# == Add the options to the flags ==
+
+CFLAGS += $(WARNINGS)
+CFLAGS += -D_DEFAULT_SOURCE
 LFLAGS += $(CFLAGS)
 
 # == Directories ==
@@ -44,26 +58,33 @@ SOURCES := $(foreach DIR, $(SRCDIRS), $(wildcard $(DIR)/*.c))
 OBJECTS = $(patsubst $(SRC)%.c, $(OBJ)%.o, $(SOURCES))
 
 # == Fun color output ==
-BEG =	echo -e -n "  \033[32m$(1)$(2)...\033[0m" ; echo -n > /tmp/.`whoami`-build-errors
+OFF = \033[1;0m
+BOLD =\033[1;1m
+BLUE = $(BOLD)\033[1;34m
+GREEN = $(BOLD)\033[1;32m
+RED = $(BOLD)\033[1;31m
+YELLOW = $(BOLD)\033[1;33m
+
+BEG =	echo -e -n "$(1)$(2)$(OFF) \033[1m$(3)...$(OFF)" ; echo -n > /tmp/.`whoami`-build-errors
 END =	if [[ -s /tmp/.`whoami`-build-errors ]] ; then \
-		echo -e -n "\r\033[1;33m$(1)$(2)\033[0m\n"; \
-		cat /tmp/.`whoami`-build-errors; \
+		if cut -d':' -f4 /tmp/.`whoami`-build-errors | grep -q error; then \
+			echo -e -n "\r$(RED)$(2)$(OFF) \033[1m$(3)   $(OFF)\n"; \
+			cat /tmp/.`whoami`-build-errors; \
+			rm /tmp/.`whoami`-build-errors || true; \
+			exit -1; \
+		else \
+			echo -e -n "\r$(YELLOW)$(2)$(OFF) \033[1m$(3)   $(OFF)\n"; \
+			cat /tmp/.`whoami`-build-errors; \
+			rm /tmp/.`whoami`-build-errors || true; \
+		fi \
 	else \
-		echo -e -n "\r  \033[1;32m$(1)$(2)\033[0m\033[K\n"; \
+		echo -e -n "\r$(1)$(2)$(OFF) \033[1m$(3)$(OFF)\033[K\n"; \
 	fi
 
-INFO = echo -e -n "\r  \033[1;34m$(1)$(2)\033[0m\n"
+INFO = echo -e -n "$(GREEN)$(1) $(2)$(OFF)\n"
 
-ERRORFUNC = echo -e " \033[1;31m! Fatal error encountered.\033[0m"; \
-	cat /tmp/.`whoami`-build-errors; \
-	exit 1;
-
-ERRORS = 2>>/tmp/.`whoami`-build-errors || { $(call ERRORFUNC) }
-
-ERRORSS = >>/tmp/.`whoami`-build-errors || { $(call ERRORFUNC) }
-
-BEGRM = echo -e -n "  \033[31m$(1)$(2)...\033[0m" && echo -n > /tmp/.`whoami`-build-errors
-ENDRM = echo -e -n "\r  \033[1;31m$(1)$(2)\033[0m\033[K\n"
+ERRORS = 2>>/tmp/.`whoami`-build-errors || true
+ERRORSS = >>/tmp/.`whoami`-build-errors || true
 
 # == Build rules ==
 
@@ -75,10 +96,10 @@ ENDRM = echo -e -n "\r  \033[1;31m$(1)$(2)\033[0m\033[K\n"
 .SUFFIXES:
 
 all: init $(TARGET)
-	@$(call INFO, "--", "Building $(PROJECT)...Done!");
+	@$(call INFO,"::","Building $(PROJECT)... Done!");
 
 init:
-	@$(call INFO, "--", "Building $(PROJECT)...");
+	@$(call INFO,"::","Building $(PROJECT)...");
 
 run: # Won't recompile
 	@echo ""
@@ -88,18 +109,22 @@ run: # Won't recompile
 	@echo ""
 
 $(OBJ)%.o: $(SRC)%.c
-	@$(call BEG, "CC", "$<")
+	@$(call BEG,$(BLUE),"  -\> CC","$@ \<-- $^")
 	@mkdir -p $(dir $@)
 	@$(CC) -c $< -o $@ $(CFLAGS) $(ERRORS)
-	@$(call END, "CC", "$<")
+	@$(call END,$(BLUE),"  -\> CC","$@ \<-- $^")
 
 $(TARGET): $(OBJECTS)
-	@$(call BEG, "LD", "$<")
+	@$(call BEG,$(BLUE),"  -\> LD","$@ \<-- $^")
 	@mkdir -p $(dir $@)
 	@$(CC) $(OBJECTS) -o $(TARGET) $(LFLAGS) $(ERRORS)
-	@$(call END, "LD", "$<")
+	@$(call END,$(BLUE),"  -\> LD","$@ \<-- $^")
 
 clean:
-	@$(call BEGRM, "RM", "$(BIN) $(OBJ)")
-	@$(RM) -rf $(BIN) $(OBJ)
-	@$(call ENDRM, "RM", "$(BIN) $(OBJ)")
+	@$(call INFO,"::","Removing generated files...");
+	@$(call BEG,$(BLUE),"  -\> RM","$(BIN)")
+	@$(RM) -rf $(BIN)
+	@$(call END,$(BLUE),"  -\> RM","$(BIN)")
+	@$(call BEG,$(BLUE),"  -\> RM","$(OBJ)")
+	@$(RM) -rf $(OBJ)
+	@$(call END,$(BLUE),"  -\> RM","$(OBJ)")
